### ISSUE TITLE
classNotFound exception

### ISSUE THREAD

**Issue by pankajmi** [damienclaveau/kafka-graphite#4]
I am using kafka-0.8.1.1 and followed the instructions for setting up the kafka broker and when I start kafka server I get following exception -

java.lang.ClassNotFoundException: com/criteo/kafka/KafkaGraphiteMetricsReporter[
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:186)
	at kafka.utils.Utils$.createObject(Utils.scala:438)
	at kafka.metrics.KafkaMetricsReporter$$anonfun$startReporters$1.apply(KafkaMetricsReporter.scala:59)
	at kafka.metrics.KafkaMetricsReporter$$anonfun$startReporters$1.apply(KafkaMetricsReporter.scala:58)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at kafka.metrics.KafkaMetricsReporter$.startReporters(KafkaMetricsReporter.scala:58)
	at kafka.Kafka$.main(Kafka.scala:36)
	at kafka.Kafka.main(Kafka.scala)

**Comment by zmstone** [comment]
hi, did you manage to get it to work?
I had the same issue. then I tried to copy all the dependencies to kafka libs (no overwrite), now the error is: java.lang.NoClassDefFoundError: scala/collection/convert/WrapAsScala
this is super weird because WrapAsScala is newly introduced in scala 2.10 or something, but it's 2.9.2 for kafka.

**Comment by pankajmi** [comment]
Yes it worked, I added kafka-graphite-1.0.0.jar to kafka lib and added following properties to server.properties

kafka.metrics.reporters=com.criteo.kafka.KafkaGraphiteMetricsReporter,kafka.metrics.KafkaCSVMetricsReporter
kafka.graphite.metrics.reporter.enabled=true

kafka.graphite.metrics.host=<host>
kafka.graphite.metrics.port=<port>
kafka.graphite.metrics.group=<name>
#

**Comment by zmstone** [comment]
now that I figured the things in [] is simply an example of other optional reporters.... I feel so stupid.
perhaps you can close this issue now ?
thanks a lot!
